### ISSUE TITLE
Error messages about Message: no such element: Unable to locate element: {"method":"id","selector":"id_login"}

### ISSUE THREAD

**Issue by jiachengxu** [bonfy/leetcode#23]
Hi,
Thanks for your script and it saves my life to archive my solutions! 
I tried to use the script to update my leetcode solution, and everytime I got the same error messages everytime as follows:
`Traceback (most recent call last):
  File "leetcode_generate.py", line 603, in <module>
    do_job(leetcode)
  File "leetcode_generate.py", line 580, in do_job
    leetcode.load()
  File "leetcode_generate.py", line 253, in load
    self.login()
  File "leetcode_generate.py", line 205, in login
    driver.find_element_by_id('id_login').send_keys(usr)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 351, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 955, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"id_login"}
  (Session info: headless chrome=69.0.3497.100)
  (Driver info: chromedriver=2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85),platform=Mac OS X 10.14.0 x86_64)
`
Any ideas about how to solve this issue?

Thanks,
Jiacheng

**Comment by bonfy** [comment]
@jiachengxu 

Leetcode change its Login Page again.

Now I have fixed it. You can try it now.

**Comment by jiachengxu** [comment]
Ok, thanks for that! Your tool is really great!!!
