### ISSUE TITLE
报错WebDriverException

### ISSUE THREAD

**Issue by rzhangpku** [bonfy/leetcode#27]
`Traceback (most recent call last):
  File "leetcode_generate.py", line 627, in <module>
    do_job(leetcode)
  File "leetcode_generate.py", line 604, in do_job
    leetcode.load()
  File "leetcode_generate.py", line 267, in load
    self.login()
  File "leetcode_generate.py", line 210, in login
    driver.get(LOGIN_URL)
  File "/Users/zhangrong/anaconda/envs/py3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/zhangrong/anaconda/envs/py3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/zhangrong/anaconda/envs/py3/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"93071366BB94A230ABBDCD535AED2AFC","isDefault":true,"type":"default"},"id":1,"name":"","origin":"://"}
  (Session info: chrome=73.0.3683.75)
  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.14.3 x86_64)`
谢谢大佬！

**Comment by bonfy** [comment]
按照这个做了么？

https://github.com/bonfy/leetcode/blob/master/README_leetcode_generate.md

检查下chromium安装的路径 还有 网络自己访问下 能不能上 leetcode

**Comment by rzhangpku** [comment]
搞定了，谢谢大佬！！！
