### ISSUE TITLE
run "python3 leetcode_generate.py" get back of these....

### ISSUE THREAD

**Issue by GeorgeJu95** [bonfy/leetcode#33]
Traceback (most recent call last):
  File "leetcode_generate.py", line 628, in <module>
    do_job(leetcode)
  File "leetcode_generate.py", line 605, in do_job
    leetcode.load()
  File "leetcode_generate.py", line 268, in load
    self.login()
  File "leetcode_generate.py", line 209, in login
    chrome_options=options, executable_path=executable_path
  File "/home/levi/leetcode/venv/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/levi/leetcode/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/levi/leetcode/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/levi/leetcode/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/home/levi/leetcode/venv/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

**Comment by bonfy** [comment]
@GeorgeJu95 

`Message: unknown error: cannot find Chrome binary`  I guess you need to setup Chrome binary first.

Please follow https://github.com/bonfy/leetcode/blob/master/README_leetcode_generate.md
